version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:18.17
    steps:
      # Checkout the code as the first step.
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:YVBLLj/i6DEPkV5HNArcR/4Wd/iQyN3kGizfLmPvMu4"
      - run:
          name: Update known hosts
          command: ssh-keyscan -H 161.35.144.184 >> ~/.ssh/known_hosts
      - run:
          name: update-code
          command: ssh root@161.35.144.184 "cd /opt/illustrarama/illustrarama-core; git pull"
      - run:
          name: digital-ocean-backend
          command: ssh root@161.35.144.184 "source ~/.nvm/nvm.sh; bash /opt/illustrarama/illustrarama-core/deploy.sh"

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main